import defaultMdxComponents from "fumadocs-ui/mdx";
import { BiErrorAlt } from "react-icons/bi";
import { FiCheck, FiDownload, FiInfo, FiUser, FiChevronDown, FiChevronRight, FiX } from "react-icons/fi";
import { IoWarningOutline } from "react-icons/io5";

import {
  NumberInput,
  NumberInputContext,
  NumberInputControl,
  NumberInputDecrementTrigger,
  NumberInputIncrementTrigger,
  NumberInputInput,
  NumberInputLabel,
  NumberInputProvider,
  NumberInputRoot,
} from "@/registry/thornberry/components/number-input";

import {
  Pagination,
  PaginationContext,
  PaginationEllipsis,
  PaginationItem,
  PaginationNextTrigger,
  PaginationPrevTrigger,
  PaginationProvider,
  PaginationRoot,
} from "@/registry/thornberry/components/pagination";

import {
  Collapsible,
  CollapsibleContent,
  CollapsibleContext,
  CollapsibleProvider,
  CollapsibleRoot,
  CollapsibleTrigger,
} from "@/registry/thornberry/components/collapsible";

import {
  Combobox,
  ComboboxClearTrigger,
  ComboboxContent,
  ComboboxContext,
  ComboboxControl,
  ComboboxInput,
  ComboboxItem,
  ComboboxItemGroup,
  ComboboxItemGroupLabel,
  ComboboxLabel,
  ComboboxPositioner,
  ComboboxProvider,
  ComboboxRoot,
  ComboboxTrigger,
} from "@/registry/thornberry/components/combobox";

import {
  Carousel,
  CarouselContext,
  CarouselControl,
  CarouselIndicator,
  CarouselIndicatorGroup,
  CarouselItem,
  CarouselItemGroup,
  CarouselNextTrigger,
  CarouselPrevTrigger,
  CarouselProvider,
  CarouselRoot,
} from "@/registry/thornberry/components/carousel";

import {
  Menu,
  MenuArrow,
  MenuArrowTip,
  MenuCheckboxItem,
  MenuContent,
  MenuItem,
  MenuItemGroup,
  MenuItemGroupLabel,
  MenuItemIndicator,
  MenuItemText,
  MenuPositioner,
  MenuProvider,
  MenuRadioItem,
  MenuRadioItemGroup,
  MenuRoot,
  MenuSeparator,
  MenuTrigger,
  MenuTriggerItem,
} from "@/registry/thornberry/components/menu";

import {
  Tooltip,
  TooltipArrow,
  TooltipArrowTip,
  TooltipContent,
  TooltipPositioner,
  TooltipProvider,
  TooltipRoot,
  TooltipTrigger,
} from "@/registry/thornberry/components/tooltip";

import {
  Popover,
  PopoverArrow,
  PopoverArrowTip,
  PopoverCloseTrigger,
  PopoverContent,
  PopoverContext,
  PopoverPositioner,
  PopoverProvider,
  PopoverRoot,
  PopoverTrigger,
} from "@/registry/thornberry/components/popover";

import {
  Dialog,
  DialogBackdrop,
  DialogCloseTrigger,
  DialogContent,
  DialogContext,
  DialogDescription,
  DialogPositioner,
  DialogProvider,
  DialogRoot,
  DialogTitle,
  DialogTrigger,
} from "@/registry/thornberry/components/dialog";

import {
  Slider,
  SliderContext,
  SliderControl,
  SliderLabel,
  SliderMarker,
  SliderProvider,
  SliderRange,
  SliderRoot,
  SliderThumb,
  SliderTrack,
  SliderValueText,
} from "@/registry/thornberry/components/slider";

import {
  Switch,
  SwitchContext,
  SwitchControl,
  SwitchHiddenInput,
  SwitchLabel,
  SwitchProvider,
  SwitchRoot,
  SwitchThumb,
} from "@/registry/thornberry/components/switch";

import {
  Tabs,
  TabsContent,
  TabsContext,
  TabsIndicator,
  TabsList,
  TabsProvider,
  TabsRoot,
  TabsTrigger,
} from "@/registry/thornberry/components/tabs";

import {
  Accordion,
  AccordionContext,
  AccordionItem,
  AccordionItemContent,
  AccordionItemIndicator,
  AccordionItemTrigger,
  AccordionProvider,
  AccordionRoot,
} from "@/registry/thornberry/components/accordion";
import {
  Alert,
  AlertDescription,
  AlertIcon,
  AlertRoot,
  AlertTitle,
} from "@/registry/thornberry/components/alert";
import {
  Avatar,
  AvatarFallback,
  AvatarImage,
  AvatarRoot,
} from "@/registry/thornberry/components/avatar";
import { Badge } from "@/registry/thornberry/components/badge";
import { Button } from "@/registry/thornberry/components/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardRoot,
  CardTitle,
} from "@/registry/thornberry/components/card";
import {
  CheckboxControl,
  CheckboxHiddenInput,
  CheckboxIndicator,
  CheckboxLabel,
  CheckboxRoot,
} from "@/registry/thornberry/components/checkbox";
import { Input } from "@/registry/thornberry/components/input";

import type { MDXComponents } from "mdx/types";

export const getMDXComponents = (components?: MDXComponents): MDXComponents => {
  return {
    ...defaultMdxComponents,
    Menu,
    MenuArrow,
    MenuArrowTip,
    MenuCheckboxItem,
    MenuContent,
    MenuItem,
    MenuItemGroup,
    MenuItemGroupLabel,
    MenuItemIndicator,
    MenuItemText,
    MenuPositioner,
    MenuProvider,
    MenuRadioItem,
    MenuRadioItemGroup,
    MenuRoot,
    MenuSeparator,
    MenuTrigger,
    MenuTriggerItem,
    Tooltip,
    TooltipArrow,
    TooltipArrowTip,
    TooltipContent,
    TooltipPositioner,
    TooltipProvider,
    TooltipRoot,
    TooltipTrigger,
    Popover,
    PopoverArrow,
    PopoverArrowTip,
    PopoverCloseTrigger,
    PopoverContent,
    PopoverContext,
    PopoverPositioner,
    PopoverProvider,
    PopoverRoot,
    PopoverTrigger,
    Dialog,
    DialogBackdrop,
    DialogCloseTrigger,
    DialogContent,
    DialogContext,
    DialogDescription,
    DialogPositioner,
    DialogProvider,
    DialogRoot,
    DialogTitle,
    DialogTrigger,
    Accordion,
    AccordionContext,
    AccordionItem,
    AccordionItemContent,
    AccordionItemIndicator,
    AccordionItemTrigger,
    AccordionProvider,
    AccordionRoot,
    Alert,
    AlertDescription,
    AlertIcon,
    AlertRoot,
    AlertTitle,
    Avatar,
    AvatarRoot,
    AvatarImage,
    AvatarFallback,
    Badge,
    BiErrorAlt,
    Button,
    Card,
    CardRoot,
    CardContent,
    CardDescription,
    CardFooter,
    CardHeader,
    CardTitle,
    Carousel,
    CarouselContext,
    CarouselControl,
    CarouselIndicator,
    CarouselIndicatorGroup,
    CarouselItem,
    CarouselItemGroup,
    CarouselNextTrigger,
    CarouselPrevTrigger,
    CarouselProvider,
    CarouselRoot,
    CheckboxControl,
    Collapsible,
    CollapsibleContent,
    CollapsibleContext,
    CollapsibleProvider,
    CollapsibleRoot,
    CollapsibleTrigger,
    Combobox,
    ComboboxClearTrigger,
    ComboboxContent,
    ComboboxContext,
    ComboboxControl,
    ComboboxInput,
    ComboboxItem,
    ComboboxItemGroup,
    ComboboxItemGroupLabel,
    ComboboxLabel,
    ComboboxPositioner,
    ComboboxProvider,
    ComboboxRoot,
    ComboboxTrigger,
    NumberInput,
    NumberInputContext,
    NumberInputControl,
    NumberInputDecrementTrigger,
    NumberInputIncrementTrigger,
    NumberInputInput,
    NumberInputLabel,
    NumberInputProvider,
    NumberInputRoot,
    Pagination,
    PaginationContext,
    PaginationEllipsis,
    PaginationItem,
    PaginationNextTrigger,
    PaginationPrevTrigger,
    PaginationProvider,
    PaginationRoot,

    CheckboxHiddenInput,
    CheckboxIndicator,
    CheckboxLabel,
    CheckboxRoot,
    FiCheck,
    FiChevronDown,
    FiChevronRight,
    FiDownload,
    FiInfo,
    FiX,
    FiUser,
    Input,
    IoWarningOutline,
    Tabs,
    TabsContent,
    TabsContext,
    TabsIndicator,
    TabsList,
    TabsProvider,
    TabsRoot,
    TabsTrigger,
    Slider,
    SliderContext,
    SliderControl,
    SliderLabel,
    SliderMarker,
    SliderProvider,
    SliderRange,
    SliderRoot,
    SliderThumb,
    SliderTrack,
    SliderValueText,
    Switch,
    SwitchContext,
    SwitchControl,
    SwitchHiddenInput,
    SwitchLabel,
    SwitchProvider,
    SwitchRoot,
    SwitchThumb,
    ...components,
  };
};
