/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatIndexRouteImport } from './routes/$/index'
import { Route as ApiSearchRouteImport } from './routes/api/search'

const SplatIndexRoute = SplatIndexRouteImport.update({
  id: '/$/',
  path: '/$/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/api/search': typeof ApiSearchRoute
  '/$': typeof SplatIndexRoute
}
export interface FileRoutesByTo {
  '/api/search': typeof ApiSearchRoute
  '/$': typeof SplatIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/api/search': typeof ApiSearchRoute
  '/$/': typeof SplatIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/api/search' | '/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/api/search' | '/$'
  id: '__root__' | '/api/search' | '/$/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ApiSearchRoute: typeof ApiSearchRoute
  SplatIndexRoute: typeof SplatIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$/': {
      id: '/$/'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  ApiSearchRoute: ApiSearchRoute,
  SplatIndexRoute: SplatIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
